# Generated by Django 6.1.1 on 2026-10-06 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episodios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome do Episódio')),
            ],
        ),
        migrations.CreateModel(
            name='Filmes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('descricao', models.TextField(max_length=1000, verbose_name='Descrição')),
                ('categoria', models.CharField(choices=[('Ação', 'Ação'), ('Comédia', 'Comédia'), ('Drama', 'Drama'), ('Terror', 'Terror'), ('Ficção Científica', 'Ficção Científica'), ('Romance', 'Romance'), ('Suspense', 'Suspence')], max_length=20)),
                ('cartaz', models.ImageField(upload_to='cartazes/')),
            ],
        ),
        migrations.CreateModel(
            name='Temporadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temporada', models.IntegerField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('categoria', models.CharField(choices=[('Ação', 'Ação'), ('Comédia', 'Comédia'), ('Drama', 'Drama'), ('Terror', 'Terror'), ('Ficção Científica', 'Ficção Científica'), ('Romance', 'Romance'), ('Suspense', 'Suspence')], max_length=20)),
                ('lista_de_episodios', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Plataforma.episodios')),
            ],
        ),
        migrations.AddField(
            model_name='episodios',
            name='temporada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Plataforma.temporadas'),
        ),
    ]
