# Generated by Django 6.1.1 on 2026-10-06 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plataforma', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='series',
            name='lista_de_episodios',
        ),
        migrations.AddField(
            model_name='episodios',
            name='categoria',
            field=models.CharField(choices=[('Ação', 'Ação'), ('Comédia', 'Comédia'), ('Drama', 'Drama'), ('Terror', 'Terror'), ('Ficção Científica', 'Ficção Científica'), ('Romance', 'Romance'), ('Suspense', 'Suspence')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='episodios',
            name='nome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='episodios', to='Plataforma.series'),
        ),
    ]
