# Generated by Django 6.1.1 on 2026-10-06 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plataforma', '0002_remove_series_categoria_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episodios',
            old_name='nome',
            new_name='nome_da_serie',
        ),
        migrations.RemoveField(
            model_name='series',
            name='nome',
        ),
        migrations.AddField(
            model_name='episodios',
            name='episodio',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='nome_da_serie',
            field=models.CharField(default=1234, max_length=50, verbose_name='Nome da Série'),
            preserve_default=False,
        ),
    ]
