# Generated by Django 6.1.1 on 2026-10-06 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plataforma', '0003_rename_nome_episodios_nome_da_serie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episodios',
            name='temporada',
            field=models.CharField(choices=[('Temporada 1', 'Temporada 1'), ('Temporada 2', 'Temporada 2'), ('Temporada 3', 'Temporada 3'), ('Temporada 4', 'Temporada 4'), ('Temporada 5', 'Temporada 5'), ('Temporada 6', 'Temporada 6'), ('Temporada 7', 'Temporada 7'), ('Temporada 8', 'Temporada 8'), ('Temporada 9', 'Temporada 9'), ('Temporada 10', 'Temporada 10'), ('Temporada 11', 'Temporada 11'), ('Temporada 12', 'Temporada 12'), ('Temporada 13', 'Temporada 13'), ('Temporada 14', 'Temporada 14'), ('Temporada 15', 'Temporada 15'), ('Temporada 16', 'Temporada 16'), ('Temporada 17', 'Temporada 17'), ('Temporada 18', 'Temporada 18')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Temporadas',
        ),
    ]
