# Generated by Django 6.1.1 on 2026-10-06 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Autenticacao', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
